drop table if exists CAVALO
CREATE TABLE 
CAVALO
(
ID_CAVALO INT IDENTITY (1,1) PRIMARY KEY,
NOME VARCHAR(200),
RAÇA  VARCHAR(200),
COR   VARCHAR(200),
DATA_NASCIMENTO DATE,
PESO DECIMAL(10,2),
ALTURA DECIMAL(10,2)
)

INSERT INTO CAVALO (NOME,RAÇA,COR,DATA_NASCIMENTO,PESO,ALTURA)
VALUES
('VELOZ','ARABE','BRANCO','2015-01-01',480.7,1.7),
('ARASH','ARABE','BRANCO','2014-01-01',440.7,1.5),
('LETO','ARABE','BRANCO','2016-01-01',480.7,1.6),
('HILL','ARABE','BRANCO','2015-01-01',430.7,1.6),
('ARASH','ARABE','PRETO','2019-01-01',410.7,1.3),
('NIKA','ARABE','BRANCO','2014-06-21',430.7,1.3),
('LIGHT','ANDALUZ','PRETO','2018-01-01',470.7,1.5),
('LUZIA','ANDALUZ','PRETO','2017-01-01',490.7,1.5),
('CHRON','ANDALUZ','MARROM','2017-04-01',430.7,1.5),
('LEON','ANDALUZ','PRETO','2014-04-01',490.7,1.5),
('JIL','APPALOOSA','PRETO','2016-04-01',490.8,1.5),
('BILLY','APPALOOSA','BRANCO','2016-07-01',500.8,1.8),
('LANCELOT','APPALOOSA','MARROM','2011-07-01',500.8,1.7)


CREATE TABLE VITORIAS
(
ID_CAVALO INT,
QUANTIDADE INT
)
INSERT INTO VITORIAS
VALUES
(1,10),
(2,12),
(3,13),
(4,14),
(6,21),
(7,1),
(8,2),
(9,9)

--SELECT COUNT(*) CONTAGEM_T FROM CAVALO
--GERAL 
SELECT 
	 
	COUNT(ID_CAVALO) CONTAGEM_ID ,SUM(PESO) SOMATORIA_PESO
FROM CAVALO

--SEM GROUP BY = ERRO
SELECT 
	COUNT(*),
	COUNT(ID_CAVALO) CONTAGEM_ID ,
	RAÇA
	FROM CAVALO

--GROUP BY
SELECT	 
	COUNT(ID_CAVALO) CONTAGEM_ID ,
	SUM(PESO) SOMA_PESO,
	RAÇA
	FROM CAVALO
	GROUP BY RAÇA
 
 --GROUP BY RAÇA E COR
SELECT 	
	COUNT(ID_CAVALO) CONTAGEM_ID ,
	RAÇA,
	COR
	FROM CAVALO
	GROUP BY RAÇA,COR 	
	ORDER BY RAÇA,COR

SELECT 
SUM(PESO) SOMA_PESO,
AVG(PESO) AVG_PESO,
MIN(DATA_NASCIMENTO) MAIS_VELHO,
MAX(DATA_NASCIMENTO) MAIS_NOVO,
COUNT(*) CONTAGEM_GERAL,
COUNT(ID_CAVALO) CONTAGEM_ID,
COUNT(DISTINCT COR) CONTAGEM_DISTINTA_COR,
COUNT(DISTINCT RAÇA) CONTAGEM_DISTINTA_RACA
FROM CAVALO

SELECT DISTINCT RAÇA FROM CAVALO ORDER BY RAÇA
--AGRUPADO
 --GERAL
SELECT 
SUM(PESO) SOMA_PESO,
AVG(PESO) AVG_PESO,
MIN(DATA_NASCIMENTO) MAIS_VELHO,
MAX(DATA_NASCIMENTO) MAIS_NOVO,
COUNT(*) CONTAGEM_GERAL,
COUNT(ID_CAVALO) CONTAGEM_ID,
COUNT(DISTINCT COR) CONTAGEM_DISTINTA_COR,
RAÇA
FROM CAVALO
GROUP BY RAÇA


--AGRUPADO COM WHERE
 
SELECT 
SUM(PESO) SOMA_PESO,
AVG(PESO) AVG_PESO,
COUNT(ID_CAVALO) CONTAGEM_ID,
COR,
RAÇA
FROM CAVALO
WHERE (RAÇA = 'ANDALUZ' AND COR = 'PRETO') OR  (RAÇA = 'ARABE' AND COR = 'BRANCO')
GROUP BY RAÇA,COR 
ORDER BY RAÇA, COR

--AGRUPADO COM FUNÇÕES
 
SELECT 
AVG( DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE()) ) MEDIA_IDADE,
COR,
RAÇA
FROM CAVALO 
GROUP BY RAÇA,COR ORDER BY RAÇA, COR

--GROUP BY COM FUNÇÕES

SELECT 
AVG( DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE()) ) MEDIA_IDADE,

CASE 
WHEN ALTURA <=1.6 THEN 'BAIXO'
WHEN ALTURA > 1.6 THEN 'ALTO' END ESTATURA
FROM CAVALO 

GROUP BY 

CASE 
WHEN ALTURA <=1.6 THEN 'BAIXO'
WHEN ALTURA > 1.6 THEN 'ALTO' END


--
SELECT 
RAÇA, SUM(VITORIAS.QUANTIDADE) VITORIAS
FROM CAVALO INNER JOIN VITORIAS ON CAVALO.ID_CAVALO = VITORIAS.ID_CAVALO
GROUP BY  RAÇA

SELECT 
RAÇA, ISNULL(SUM(VITORIAS.QUANTIDADE),0) VITORIAS
FROM CAVALO LEFT JOIN VITORIAS ON CAVALO.ID_CAVALO = VITORIAS.ID_CAVALO
GROUP BY  RAÇA

--HAVING
SELECT 
COUNT(*) CONTAGEM,
RAÇA 
FROM CAVALO 
WHERE COR = 'BRANCO'
GROUP BY RAÇA

 

--HAVING
SELECT 
COUNT(*) CONTAGEM,
RAÇA 
FROM CAVALO 
WHERE COR = 'BRANCO'
GROUP BY RAÇA
HAVING COUNT(*)=1


SELECT 
COUNT(*) CONTAGEM,
RAÇA ,
SUM(PESO) PESO,AVG(ALTURA)
FROM CAVALO  
GROUP BY RAÇA
HAVING AVG(ALTURA)>2

SELECT COUNT(*) FROM CAVALO  HAVING  AVG(ALTURA)<2

SELECT COUNT(*) FROM CAVALO  HAVING SUM(PESO)>100


 SELECT MIN(ALTURA) BAIXO, MAX(ALTURA) ALTO,RAÇA 
 FROM CAVALO
 GROUP BY RAÇA

 SELECT  ALTURA BAIXO, ALTURA ALTO,ID_CAVALO 
 FROM CAVALO
 