/*
FUNÇÃO ESCALAR - RETORNA VALOR UNICO

*/

--EX 1 QUERO TRATAR UM CAMPO
CREATE FUNCTION VENDA.LIMPEZA(@ST VARCHAR(1000))
RETURNS VARCHAR(1000)
BEGIN
   RETURN(UPPER(TRIM(@ST)))
END

SELECT VENDA.LIMPEZA(' TEXto Ferrado')

--EX 2 QUERO O VALOR QUADRADO DE UMA VARIAVEL
CREATE FUNCTION VENDA.QUADRADO(@NUMERO INT)
RETURNS INT
BEGIN
   RETURN(@NUMERO*@NUMERO)
END

SELECT VENDA.QUADRADO(4) v16

/*
FUNÇÃO TABULARES- RETORNA VALOR UNICO

*/
-- 

--EX 1 INLINE 
 
CREATE FUNCTION VENDA.TABELINHA(@FILTRO VARCHAR(500))
RETURNS  TABLE
AS
RETURN
(
SELECT * FROM [VENDA].[PRODUTO] WHERE NOME = @FILTRO
)

SELECT * FROM  VENDA.TABELINHA ('HL Road Frame - Black, 58')
  
CREATE FUNCTION VENDA.AGREGADO (@FILTRO VARCHAR(500))
RETURNS  TABLE
AS
RETURN
(

SELECT PR.NOME, SUM(LINHAS) VALOR_TOTAL, SUM(QUANTIDADE_PEDIDO) QUANTIDADE
FROM [VENDA].[PEDIDO] P
LEFT JOIN [VENDA].[DETALHE_PEDIDO] DP ON P.ID_PEDIDO = DP.ID_PEDIDO
LEFT JOIN [VENDA].[PRODUTO] PR ON DP.ID_PRODUTO = PR.ID_PRODUTO
WHERE PR.NOME = @FILTRO
GROUP BY  PR.NOME
)

SELECT * FROM  VENDA.TABELINHA ('HL Road Frame - Black, 58')

CREATE FUNCTION VENDA.ATUALIZA_COR (@COR VARCHAR(200))
RETURNS @PRODUTO_COR
TABLE 
(
    PRODUTO varchar(500), COR VARCHAR(50), NOVA_COR  VARCHAR(MAX)
)
AS
BEGIN
INSERT INTO @PRODUTO_COR
SELECT NOME,COR,NULL FROM VENDA.PRODUTO
 
UPDATE @PRODUTO_COR SET NOVA_COR = CONCAT('SERÁ ALTERADO A COR',COR,@COR)

RETURN 
END

