CREATE VIEW   VENDA.VIEW_PRODUTO_PEDIDO 
AS

SELECT PR.NOME, SUM(LINHAS) VALOR_TOTAL, SUM(QUANTIDADE_PEDIDO) QUANTIDADE
FROM [VENDA].[PEDIDO] P
LEFT JOIN [VENDA].[DETALHE_PEDIDO] DP ON P.ID_PEDIDO = DP.ID_PEDIDO
LEFT JOIN [VENDA].[PRODUTO] PR ON DP.ID_PRODUTO = PR.ID_PRODUTO
GROUP BY  PR.NOME

ALTER VIEW   VENDA.VIEW_PRODUTO_PEDIDO 
AS

SELECT PR.NOME,PR.NUMERO_PRODUTO, SUM(LINHAS) VALOR_TOTAL, SUM(QUANTIDADE_PEDIDO) QUANTIDADE
FROM [VENDA].[PEDIDO] P
LEFT JOIN [VENDA].[DETALHE_PEDIDO] DP ON P.ID_PEDIDO = DP.ID_PEDIDO
LEFT JOIN [VENDA].[PRODUTO] PR ON DP.ID_PRODUTO = PR.ID_PRODUTO

GROUP BY  PR.NOME,PR.NUMERO_PRODUTO

DROP VIEW VENDA.VIEW_PRODUTO_PEDIDO 