--comando delete 
BEGIN TRANSACTION
DELETE FROM CANAL WHERE ID_CANAL = 1
 --comando insert 1 
 INSERT INTO CANAL 
 SELECT 'MTV',
 '1988-01-01',
 'ASTRID THUNDERBIRD','EDITORA ABRIL',0
  --comando insert 2
  INSERT INTO CANAL VALUES(
  'GMV',
 '1988-01-01',
 'ASTRID WINTERBIRD','EDITORA MAIO',0)
 --comando insert into 
SELECT TOP 20000 * INTO #CANAL_TESTE FROM CANAL

--truncate table
TRUNCATE TABLE #CANAL_TESTE

--insert com select
INSERT INTO   #CANAL_TESTE
SELECT NOME_CANAL,
DATA_FUNDACAO,
NOME_FUNDADOR,
GRUPO,
VALOR_MERCADO FROM CANAL

--SUBQUERY NO WHERE
 CREATE TABLE #ANO (ANO INT)
 INSERT INTO #ANO
 VALUES (2019),(2009)

SELECT * FROM FILMES WHERE ANO IN
( 
 SELECT ANO FROM #ANO
 )

