--DELETANDO VALORES
SELECT * FROM CANAL

-- DELETE SEM WHERE- ALTAMENTE NÃO RECOMENDAVEL
DELETE  CANAL

DELETE  CANAL WHERE GRUPO = 'REDE GLOBO'
-- SE CASO O RESULTADO DE LINHAS AFETADAS FOR MAIOR QUE O PLANEJADO, VERIFICAR O QUE HOUVE
--DELETE COM WHERE
--ANTES DE DAR UM DELETE, FAÇA UM "SELECT" COM A MESMA CLAUSULA PARA VALIDAR
--SELECT * FROM CANAL WHERE ID_CANAL = 1
-- O VALOR RETORNADO VAI SER O MESMO QUE SERÁ EXCLUIDO
DELETE  CANAL WHERE GRUPO = 'REDE GLOBO' and ID_CANAL = 1 

-- TRUNCATE TABLE
-- TRUNCATE "PARECE" COM O DELETE, PORÉM ELE ZERA OS IDENTITYS E NÃO EXISTE A POSSIBILIDADE DE FILTRAR A OPERAÇÃO, ELE DELETA TUDO
TRUNCATE TABLE CANAL


DELETE MINIATURA
--SET VALOR = MINIATURA_2.VALOR
FROM MINIATURA_2 
WHERE MINIATURA.NOME = MINIATURA_2.NOME
