CREATE TABLE CRIANCA
(
ID_CRIANCA INT IDENTITY (1,1) PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
NOME_MAE VARCHAR(100),
DATA_NASCIMENTO DATE NOT NULL,
DATA_REGISTRO DATETIME DEFAULT GETDATE(),
CPF VARCHAR(100) UNIQUE NOT NULL
)

CREATE TABLE PET
(
ID_PET INT IDENTITY (100,10),
NOME VARCHAR(100) NOT NULL,
CRIANCA INT,
CONSTRAINT FK_CRIANCA FOREIGN KEY (CRIANCA) REFERENCES CRIANCA(MATRICULA),
CONSTRAINT PK_PET PRIMARY KEY (ID_PET)

)


ALTER TABLE CRIANCA ADD RENDA DECIMAL(10,2)
ALTER TABLE CRIANCA ADD CONSTRAINT CK_RENDA CHECK  (RENDA >0)

ALTER TABLE CRIANCA DROP CONSTRAINT CK_RENDA
ALTER TABLE CRIANCA DROP COLUMN RENDA


INSERT INTO CRIANCA (NOME,NOME_MAE,DATA_NASCIMENTO,CPF)
VALUES
('CARLINHOS', 'MIRANDA','2022-01-01','111111111'),
('LOLA', 'LURDES','2022-01-01','222222222'),


INSERT INTO PET (NOME,CRIANCA)
VALUES
("AUAU",1),
("REX",2)


SELECT * FROM CRIANCA
SELECT * FROM PET