--SELECT COMUM
SELECT * FROM [fit_alunos].dbo.funcionarios
SELECT * FROM funcionarios
--SELECT TOP 
SELECT TOP 11 * FROM FUNCIONARIOS --ORDER BY NOME
--SELECT DISTINCT
SELECT DISTINCT NOME FROM FUNCIONARIOS ORDER BY NOME
--SELECT ALIAS
SELECT FUNCIONARIOS.NOME,
	   FUNCIONARIOS.SOBRENOME
	   FROM FUNCIONARIOS

--ALIAS
SELECT * FROM FUNCIONARIOS AS F --OU F
--ALIAS COLUNA
SELECT F.NOME AS NOME_FUNCIONARIO ,
	   SOBRENOME = F.SOBRENOME,
	   F.CARGO CARGO_FUNCIONARIO,
	   F.EMAIL AS [EMAIL FUNC],
	   BONUS AS 'BONUS DO FUNC',
	   F.SALARIO + F.BONUS AS SALARIO_TOTAL
--INTO #TABELA_TEMP
FROM FUNCIONARIOS  F
 

--SELECT COM WHERE (<,<=,=,>=,>) BETWEEN
--CREATE TABLE AMIGO1 (NOME  VARCHAR) 
SELECT * FROM FUNCIONARIOS WHERE BONUS > 600
SELECT * FROM FUNCIONARIOS WHERE BONUS < 600
SELECT * FROM FUNCIONARIOS WHERE BONUS <= 700
SELECT * FROM FUNCIONARIOS WHERE SALARIO <= 2000
SELECT * FROM FUNCIONARIOS WHERE BONUS BETWEEN 0 AND 140

SELECT *,BONUS + SALARIO SALARIO__BONUS
FROM FUNCIONARIOS WHERE BONUS + SALARIO BETWEEN 0 AND 4000

SELECT *,BONUS + SALARIO SALARIO__BONUS 
FROM FUNCIONARIOS
WHERE BONUS + SALARIO > 1000
ORDER BY SALARIO__BONUS,1,2

---WHERE BONUS + SALARIO BETWEEN 0 AND 4000

SELECT * FROM FUNCIONARIOS WHERE BONUS >=0 AND BONUS <= 140
SELECT SOBRENOME FROM funcionarios WHERE NOME = 'jUAN' 
SELECT * FROM funcionarios WHERE NOME != 'jUAN'  -- <>

--SELECT COM WHERE - AND
SELECT * FROM funcionarios WHERE NOME != 'jUAN'
AND BONUS >= 700

SELECT * FROM funcionarios WHERE SALARIO = 3000
AND CARGO = 'Sapateiro'

SELECT * FROM funcionarios WHERE SALARIO = 3000
AND  CARGO = 'Professor'
--SELECT COM WHERE - OR
SELECT * FROM funcionarios WHERE SALARIO = 3000
OR  CARGO = 'Professor'
--SELECT COM WHERE - NULL
SELECT * FROM funcionarios WHERE CARGO IS NULL
SELECT * FROM funcionarios WHERE CARGO IS NOT NULL

--SELECT COM WHERE - LIKE
SELECT * FROM FUNCIONARIOS WHERE NOME LIKE 'G%'
SELECT * FROM FUNCIONARIOS WHERE NOME LIKE '%a'
SELECT * FROM FUNCIONARIOS WHERE NOME LIKE '%ss%'
select * from funcionarios where email NOT LIKE '%@%'